import test from 'node:test';
import assert from 'node:assert/strict';
import {scryptSync} from 'node:crypto';
import {mutate,issueSession,authenticate,verifyPassword,snapshot} from '../lib/domain.js';
function setup(){const admin={id:'a',role:'admin',authVersion:1,credentials:{salt:'test-salt',hash:scryptSync('test-password','test-salt',64).toString('hex')},preferences:{name:'A'},permissions:{}};const member={id:'b',role:'member',authVersion:1,permissions:{createEvents:true,editEvents:true},preferences:{name:'B'}};const state={sessionSecret:'unit-test-secret',revision:0,accounts:[admin,member],clients:[{id:'c',name:'Test',version:1}],events:[]};return {state,admin,member}}
test('valid sessions, tampering, and logout revocation',()=>{const {state,admin}=setup();const token=issueSession(state,admin);assert.equal(authenticate(state,token).id,'a');assert.throws(()=>authenticate(state,token+'changed'),/Inicia sesión/);mutate(state,admin,{action:'logout'});assert.throws(()=>authenticate(state,token),/Inicia sesión/)});
test('password verification and private snapshot',()=>{const {state,admin}=setup();assert.equal(verifyPassword('test-password',admin.credentials),true);assert.equal(verifyPassword('incorrect',admin.credentials),false);const out=JSON.stringify(snapshot(state,admin));assert.equal(out.includes('sessionSecret'),false);assert.equal(out.includes('credentials'),false);assert.equal(out.includes(admin.credentials.hash),false)});
test('member permissions are enforced independently of frontend',()=>{const {state,member}=setup();assert.throws(()=>mutate(state,member,{action:'saveClient',name:'X'}),e=>e.status===403);assert.throws(()=>mutate(state,member,{action:'permissions',id:'a'}),e=>e.status===403);assert.throws(()=>mutate(state,member,{action:'deleteEvent',id:'x'}),e=>e.status===403)});
test('shared event creation and stale edit detection',()=>{const {state,admin,member}=setup();const b={action:'saveEvent',client:'c',title:'Visit',date:'2026-10-02',time:'09:00',type:'Visita',owner:'b',notes:'',done:false};mutate(state,member,b);const e=state.events[0];assert.equal(e.createdBy,'b');mutate(state,admin,{...b,id:e.id,version:1,title:'Changed'});assert.throws(()=>mutate(state,member,{...b,id:e.id,version:1}),e=>e.status===409);assert.equal(state.events[0].title,'Changed');assert.equal(snapshot(state,member).events.length,1)});
test('client deletion preserves live event relationships',()=>{const {state,admin}=setup();mutate(state,admin,{action:'saveEvent',client:'c',title:'Delivery',date:'2026-10-02',time:'09:00',type:'Entrega',owner:'a',notes:'',done:false});assert.throws(()=>mutate(state,admin,{action:'deleteClient',id:'c',version:1}),e=>e.status===409)});
test('preferences stay personal and permissions update immediately',()=>{const {state,admin,member}=setup();mutate(state,member,{action:'preferences',preferences:{name:'Juan',title:'Steve',color:'#ffffff',light:false,characters:true}});assert.equal(admin.preferences.name,'A');assert.equal(member.preferences.name,'Juan');mutate(state,admin,{action:'permissions',id:'b',permissions:{createClients:true,editClients:false,deleteClients:false,createEvents:true,editEvents:true,deleteEvents:false}});mutate(state,member,{action:'saveClient',name:'New',phone:'',notes:''});assert.equal(state.clients.length,2)});
test('invalid date and unregistered client cannot be saved',()=>{const {state,admin}=setup();const b={action:'saveEvent',client:'c',title:'Visit',date:'2026-02-30',time:'09:00',type:'Visita',owner:'a',notes:'',done:false};assert.throws(()=>mutate(state,admin,b),e=>e.status===400);assert.throws(()=>mutate(state,admin,{...b,date:'2026-10-02',client:'missing'}),e=>e.status===400)});
